In [1]:
import numpy as np

a = 10 # a is scalar value it has on integer, float, string. In other program might need to define.
print(a)

10


In [2]:
vector2 = [2,3,10,12,14]
print(vector2)


[2, 3, 10, 12, 14]


In [3]:
vector = np.asarray([2, 'hello', 10, 12, 14])
print(vector)

['2' 'hello' '10' '12' '14']


In [4]:
print(type(vector))

<class 'numpy.ndarray'>


In [5]:
array_= np.empty([4,2])
print(array_)
#need to initialise it to be zero. 
array_1 = np.zeros([4,3])
print(array_1)

a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)

c = a + b
print(c)
d = a * b
print(d)

mat = np.ones([3,3])*10 #5 row 3 columns 
print(mat)

[[3.95252517e-323 0.00000000e+000]
 [5.45352918e-312 3.56726866e-057]
 [5.85107551e+170 5.75297879e-066]
 [2.70048567e-056 1.41491344e-076]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [6]:
mat[0,0] = 6
print(mat[0,0])
print(mat)

6.0
[[ 6. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [7]:
mat2 = np.array(([1,-2,3,40],[4,5,7,5],[-10,8,10,23],[4,5,7,5]))
print(mat2)

[[  1  -2   3  40]
 [  4   5   7   5]
 [-10   8  10  23]
 [  4   5   7   5]]


In [8]:
print(mat2[:1])
print(mat2[0,1])
print(mat2[0,1:3])
print(mat2[3,3:4])

print(mat2[1:3,1:3])
middle = mat2[1:3,1:3]
print(mat2[1,-1])

print(mat2[-1,0])
#10
print(mat2[2,-2])
#7 in 2nd row
print(mat2[1,-2])
print(mat2[1,2])
print(mat2[1,1])
8
print(mat2[2,1])

[[ 1 -2  3 40]]
-2
[-2  3]
[5]
[[ 5  7]
 [ 8 10]]
5
4
10
7
7
5
8


In [9]:
grade = 49
if grade < 100 and grade > 50:
    print('pass')
else:
    print('fail')

fail


In [10]:
bool = (grade > 90 and grade <=100)
print(bool)

False


In [11]:
cube = ([1,3,4],[5,33,1],[3,5,6])
print(cube)

([1, 3, 4], [5, 33, 1], [3, 5, 6])


In [12]:
three_dim = np.empty([4,4,3])
print(three_dim)

[[[0.00000000e+000 5.02034658e+175 7.66959779e-042]
  [1.19023451e-047 8.67782069e-067 3.70244687e-033]
  [5.01163106e+217 5.49419094e-143 7.67614547e+218]
  [1.06396443e+224 5.77286025e+199 4.31443967e-096]]

 [[9.08366793e+223 1.48582160e-076 9.60611514e-071]
  [8.78011206e-071 2.19409753e-056 2.24729309e+174]
  [1.56605686e-076 6.00024308e-067 6.37172339e-062]
  [3.06060581e-057 1.28625693e+248 4.24948967e-086]]

 [[4.05171132e-317 2.08600674e-308 6.94753268e-310]
  [9.58487353e-322 0.00000000e+000 0.00000000e+000]
  [2.12199579e-314 5.02034658e+175 2.19183416e-076]
  [3.53740546e-057 3.40325781e+175 1.74490428e-076]]

 [[1.47763641e+248 1.16096346e-028 7.69165785e+218]
  [1.35617292e+248 1.15942117e+165 1.42697347e-071]
  [9.04730477e-067 1.33532013e+165 4.30439842e-096]
  [6.32299154e+233 6.48224638e+170 5.22411352e+257]]]


In [13]:
summation = 0
i=1
for i in range(101):
    summation = summation + i**2
print(summation)

338350


In [14]:
i= 1 
summation1= 0 
while i < 100:
    summation1 += i**2
    i +=1
print(summation1)

328350


In [15]:
#5 value  power of 
array_a = np.array([2,2,3,20,5])
power = np.empty([5]) # number of colums

i = 0 
while (i < 5):
    power[i] = array_a[i]**2
    i += 1
    print(power)
    
power2 = np.empty([2,3])

print(power2)


[4. 0. 0. 0. 0.]
[4. 4. 0. 0. 0.]
[4. 4. 9. 0. 0.]
[  4.   4.   9. 400.   0.]
[  4.   4.   9. 400.  25.]
[[7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74681717e-304 7.74860419e-304 7.74860419e-304]]


In [16]:
#3 by 2   **2 
power2_mat = np.empty([3,2])
mat_a = np.array([[1,2],[3,4],[5,6]])

for i in range(3):
    for j in range(2):
        power2_mat[i,j] = mat_a[i,j]**2
print(power2_mat)


[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]]


In [17]:
summation_i =0
i=1
while i<10:
    summation_i += i
    i += 0.000001
print(summation_i)

49500005.50199725


In [18]:
summation_1 =0 # while loop 
i=0
while i < 10:
    summation_1 += i
    i+= 1
print(summation_1)

45


In [23]:
# #3 by 2   **2 
# import numpy as np
# power2_mat = np.empty([3,2])
# mat_a = np.array([[1,2],[3,4],[5,6]])
# # print(power2_mat)
# # print(mata)

# for i in range(3):
#     for j in range(2):
#         power2_mat[i,j] = mat_a[i,j]**2
# print(power2_mat)

#3 by 2   **2 
import numpy as np
power2_mat = np.empty([3,3])
mat_a = np.array([[1,2,3],[4,3,4],[7,5,6]])
# print(power2_mat)
# print(mata)

for i in range(3):
    for j in range(3):
        power2_mat[i,j] = mat_a[i,j]**1/2
print(power2_mat)

[[0.5 1.  1.5]
 [2.  1.5 2. ]
 [3.5 2.5 3. ]]
