In [89]:
import numpy as np
import pandas as pd
import matplotlib.image as mpimg
import pandas as pd

In [90]:
data = pd.read_csv("/Users/Vani/Downloads/iris.csv")

In [91]:
data.columns = ['sepal_length','sepal_width','petal_length','petal_width','species']

In [92]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
sepal_length    149 non-null float64
sepal_width     149 non-null float64
petal_length    149 non-null float64
petal_width     149 non-null float64
species         149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [93]:
data.shape

(149, 5)

In [94]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [95]:
data['species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: species, dtype: int64

In [96]:
def substring_after(s,delim):
    return s.partition(delim)[2]

In [98]:
x = data['species'].str.split("-")

In [99]:
type(x)

pandas.core.series.Series

In [100]:
x.head()

0    [Iris, setosa]
1    [Iris, setosa]
2    [Iris, setosa]
3    [Iris, setosa]
4    [Iris, setosa]
Name: species, dtype: object

In [101]:
lst = [item[1] for item in x]

In [42]:
lst

['setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolo

In [102]:
species = pd.DataFrame(lst)

In [103]:
species.columns = ['New-Species']

In [104]:
species.head(2)

New-Species
0      setosa
1      setosa

In [105]:
new_data = pd.concat([data,species],axis=1)

In [106]:
new_data.head(2)

sepal_length  sepal_width  petal_length  petal_width      species  \
0           4.9          3.0           1.4          0.2  Iris-setosa   
1           4.7          3.2           1.3          0.2  Iris-setosa   

  New-Species  
0      setosa  
1      setosa

In [107]:
new_data.drop('species',axis=1,inplace=True)

In [108]:
new_data.head(2)

sepal_length  sepal_width  petal_length  petal_width New-Species
0           4.9          3.0           1.4          0.2      setosa
1           4.7          3.2           1.3          0.2      setosa

In [109]:
new_data.columns = ['sepal_length','sepal_width','petal_length','petal_width','species']

In [110]:
new_data.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           4.9          3.0           1.4          0.2  setosa
1           4.7          3.2           1.3          0.2  setosa

In [111]:
#Spliting the dataset in independent and dependent variables
X = new_data.iloc[:,:4].values
y = new_data['species'].values

In [114]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)


In [115]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [119]:
X_train.max()

3.1776716810069257

# Linear Kernel

In [69]:
# Using Linear Kernel
from sklearn.svm import SVC
svcclassifier = SVC(kernel = 'linear', random_state = 0)
svcclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [70]:
# Predicting the Test set results
y_pred = svcclassifier.predict(X_test)
print(y_pred)

['virginica' 'versicolor' 'setosa' 'setosa' 'setosa' 'setosa' 'versicolor'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'virginica' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor']


In [71]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([['virginica', 'virginica'],
       ['versicolor', 'versicolor'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [72]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[11  0  0]
 [ 0 11  0]
 [ 0  0  8]]


In [73]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  30
False predictions 0
Accuracy of the SVC Clasification is:  1.0


# Using polynomial kernel

In [76]:
svcclassifier = SVC(kernel = 'poly', random_state = 0)
svcclassifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = svcclassifier.predict(X_test)
print(y_pred)

['versicolor' 'versicolor' 'setosa' 'setosa' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'versicolor' 'setosa' 'versicolor'
 'versicolor' 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa'
 'virginica' 'versicolor' 'virginica' 'setosa' 'setosa' 'virginica'
 'versicolor']


In [77]:
#Comparision of actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([['virginica', 'versicolor'],
       ['versicolor', 'versicolor'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [78]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0 11  0]
 [ 0  3  5]]


In [79]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  27
False predictions 3
Accuracy of the SVC Clasification is:  0.9


# Using rbf kernel

In [80]:
svcclassifier = SVC(kernel = 'rbf', random_state = 0)
svcclassifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = svcclassifier.predict(X_test)
print(y_pred)

['virginica' 'versicolor' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'virginica' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor']


In [81]:
#Comparision of actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([['virginica', 'virginica'],
       ['versicolor', 'versicolor'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [82]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0 10  1]
 [ 0  0  8]]


In [83]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  29
False predictions 1
Accuracy of the SVC Clasification is:  0.9666666666666667


# Using sigmoid kernel

In [84]:
svcclassifier = SVC(kernel = 'sigmoid', random_state = 0)
svcclassifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = svcclassifier.predict(X_test)
print(y_pred)


['virginica' 'versicolor' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'setosa' 'virginica' 'versicolor']


In [85]:
#Comparision of actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([['virginica', 'virginica'],
       ['versicolor', 'versicolor'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [86]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  1  0]
 [ 0  9  2]
 [ 0  0  8]]


In [87]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelLinearAccuracy = corrPred/(cm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  27
False predictions 3
Accuracy of the SVC Clasification is:  0.9
