In [7]:
import numpy as np
A=np.zeros([5, 5])
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
result_x=np.random.randint(0,4)
result_y=np.random.randint(0,4)

In [9]:
def success(x,y):
    if x==result_x:
        y==result_y
        return 1



In [10]:
def out_of_range(x,y):
    if x<0 or x>4 or y<0 or y>4:
        return 1

In [11]:
def distance(x,y):
    distance = sqrt((result_x-x)^2 + (result_y-y)^2)
    return distance

In [12]:
for i in range(5):
    x_in = int(input("one integer between 0 to 4"))
    y_in = int(input("one integer between 0 to 4"))
    if success(x_in,y_in):
        print('sucessful')
        break
        
    



one integer between 0 to 41
one integer between 0 to 41
one integer between 0 to 42
one integer between 0 to 42
one integer between 0 to 43
one integer between 0 to 43
sucessful


In [27]:
elif(out_of_range(x_in,y_in)):
    print('error')
        

SyntaxError: invalid syntax (<ipython-input-27-3fc35eff900f>, line 1)

In [22]:
elif    Mugwump_home[x_in][y_in] =="X":
        print("Be carefull!you input repetitive numbers")
else:
        Mugwump_home[x_in][y_in]="X"
        print("keep trying,your distance to goal is: " , distance(x_in,y_in))
        print(Mugwump_home)  
print("Game Over!!you tried " + str(i+1) + " times! The Goal was:  " +   str(Mugwump_x) +"  " + str(Mugwump_y)) 

SyntaxError: invalid syntax (<ipython-input-22-214730d35b4b>, line 1)

In [ ]:
import random
import math
import numpy as np

Mugwump_x = random.randint(0,4)
Mugwump_y = random.randint(0,4)
Mugwump_home =[[0,0,0,0,0],
              [0,0,0,0,0],
              [0,0,0,0,0],
              [0,0,0,0,0],
              [0,0,0,0,0]]

def win(x,y):
    if x == Mugwump_x and y== Mugwump_y:
        return 1
    
def out_of_range(x,y): 
    if x<0 or x>4 or y<0 or y>4:
        return 1
    
def distance(x,y):
    dist = np.sqrt((Mugwump_x-x)**2+(Mugwump_y-y)**2)
    return dist

for i in range(5):
    x_in = int(input("input one integer between 0 to 4:"))
    y_in = int(input("input one integer between 0 to 4:"))
    if win(x_in,y_in):
        print("well done,you win!!!")
        break
    elif out_of_range(x_in,y_in):
        print("Ooopss!! your number is out of borders,try again")
    elif Mugwump_home[x_in][y_in] =="X":
        print("Be carefull!you input repetitive numbers")
    else:
        Mugwump_home[x_in][y_in]="X"
        print("keep trying,your distance to goal is: " , distance(x_in,y_in))
        print(Mugwump_home)  
print("Game Over!!you tried " + str(i+1) + " times! The Goal was:  " +   str(Mugwump_x) +"  " + str(Mugwump_y))       

input one integer between 0 to 4:-1
input one integer between 0 to 4:6
Ooopss!! your number is out of borders,try again
input one integer between 0 to 4:1
input one integer between 0 to 4:3
keep trying,your distance to goal is:  1.0
[[0, 0, 0, 0, 0], [0, 0, 0, 'X', 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
input one integer between 0 to 4:2
input one integer between 0 to 4:2
keep trying,your distance to goal is:  1.0
[[0, 0, 0, 0, 0], [0, 0, 0, 'X', 0], [0, 0, 'X', 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
input one integer between 0 to 4:2
input one integer between 0 to 4:2
Be carefull!you input repetitive numbers
