![dsia](https://static1.squarespace.com/static/5c4631190dbda3abea29db4c/t/5c465b0dc74c5024875652f7/1549343891985/?format=1500w)

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [5]:
import numpy as np

In [6]:
a = [-12, 16]
b = [12, 9]

a*b = (-12*12 + 16*9)

In [9]:
np.dot(a,b)

0

2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [10]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

a1 = [1,2,3], a2 = [4,5,6]
b1 = [4,5,6], b2 = [1,2,3]

cx1 = [2x6 - 3x5] = -3
cy1 = [3x4 - 1x6] = 6
cz1 = [1x5 - 2x4] = -3

cx2 = [5x3 - 6x2] = 3
cy2 = [6x1 - 4x3] = -6
cz2 = [4x2 - 5x1] = 3

a1 . b1 = (-3,6,-3)
a2 . b2 = (3,-6,3)

a . b = ([-3,6,-3],[3,-6,3])

In [12]:
# Below is from numpy embeded formula for Cross_Product
np.cross(a,b)

array(-300)

In [13]:
number_of_students = [1,2,3,4]

print(len(number_of_students))

4


In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
y

array([[4, 5, 6],
       [1, 2, 3]])

In [16]:
print(np.cross(x,y))

[[-3  6 -3]
 [ 3 -6  3]]


3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a = [ 1 2
      3 4]
b = [ 5 6
      7 8]

a . b = [1x5 2x6
         3x7 4x8]
a . b = [5 12
        21 32]


4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [18]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]


print(np.add(X,Y))

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [21]:
x1 = [[12.2,7.5,3.7],
    [4 ,5,6],
    [7 ,8,9]]

x2 = [[.2,.5,.7],
    [4 ,5,6],
    [7 ,8,9]]

print(np.add(x1,x2))

[[12.4  8.   4.4]
 [ 8.  10.  12. ]
 [14.  16.  18. ]]


5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [0]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

A . B = [(a1,1xb1,2 + a1,2xb1,2) + (a1,1xb2,2 + a1,2xb2,2)],
        [(a3,1xb1,3 + a3,2xb1,3) + (a3,1xb2,3 + a3,2xb2,3)]
    
A . B = [[(12x8 + 7x8) + (12x7 +7x7)],
        [(7x1 + 8x1) + (7x3 + 8x3)]]
A . B = [285,60]


6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [0]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

matrix = [-2 2 -3
          -1 1 3
           2 0 -1]

|matrix| = [(-2)x(1x(-1) - (0x3)) - 2x(((-1)x(-1) -(2x3))) + (-3)x((-1)x0 - (2x1))]

|matrix| = [8 - (-10) + 6]

|matrix| = 24


7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [0]:
a = np.array([[1., 2.], [3., 4.]])

