![alt text](https://i.imgur.com/1WaY7aA.png)


---



---



# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.16.2
Pandas:  0.24.2


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [6]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  import sys
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if sys.path[0] == '':


?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [9]:
#ANSWER:
bikes = pd.read_csv('bikeshare.csv')
print(bikes.head())

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1  


In [10]:
bikes = pd.read_table('bikeshare.csv', header = 0, sep=',')
print(bikes.head())

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1  


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [12]:

from pandas import ExcelFile  
# Nb. Need to install xlrd from 
#conda (it does not automatically install with pandas)

In [20]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df.head()

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0           1          0.2           1.4          3.5           5.1   
1           1          0.2           1.4          3.0           4.9   
2           1          0.2           1.3          3.2           4.7   
3           1          0.2           1.5          3.1           4.6   
4           1          0.2           1.4          3.6           5.0   

  Species_name  
0       Setosa  
1       Setosa  
2       Setosa  
3       Setosa  
4       Setosa

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [21]:
#ANSWER

df = pd.read_excel('Iris.xls', sheet_name='Data', header=0, usecols=[0,1,2])

df.head(3)

Species_No  Petal_width  Petal_length
0           1          0.2           1.4
1           1          0.2           1.4
2           1          0.2           1.3

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [22]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [23]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

[                                             Bank Name                City  \
 0                                 The Enloe State Bank              Cooper   
 1                  Washington Federal Bank for Savings             Chicago   
 2      The Farmers and Merchants State Bank of Argonia             Argonia   
 3                                  Fayette County Bank          Saint Elmo   
 4    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 5                                       First NBC Bank         New Orleans   
 6                                        Proficio Bank  Cottonwood Heights   
 7                        Seaway Bank and Trust Company             Chicago   
 8                               Harvest Community Bank          Pennsville   
 9                                          Allied Bank            Mulberry   
 10                        The Woodbury Banking Company            Woodbury   
 11                              First CornerStone B

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [24]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0         5 2015-01-01 00:00:00         0
1         5 2015-01-01 00:00:01         0
10        5 2015-01-01 00:00:10         0
11        5 2015-01-01 00:00:11         0
12        8 2015-01-01 00:00:12         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [26]:
#ANSWER
bikes.shape

(17379, 17)

What are the column names in `bikes`?

In [27]:
#ANSWER
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [28]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [29]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [30]:
#ANSWER
bikes['season']

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
17349    1
17350    1
17351    1
17352    1
17353    1
17354    1
17355    1
17356    1
17357    1
17358    1
17359    1
17360    1
17361    1
17362    1
17363    1
17364    1
17365    1
17366    1
17367    1
17368    1
17369    1
17370    1
17371    1
17372    1
17373    1
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64

In [31]:
bikes[['season']]

season
0           1
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           1
9           1
10          1
11          1
12          1
13          1
14          1
15          1
16          1
17          1
18          1
19          1
20          1
21          1
22          1
23          1
24          1
25          1
26          1
27          1
28          1
29          1
...       ...
17349       1
17350       1
17351       1
17352       1
17353       1
17354       1
17355       1
17356       1
17357       1
17358       1
17359       1
17360       1
17361       1
17362       1
17363       1
17364       1
17365       1
17366       1
17367       1
17368       1
17369       1
17370       1
17371       1
17372       1
17373       1
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

In [32]:
print(type(bikes['season']))
print(type(bikes[['season']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


How would we use object notation to show the first 4 rows of `atemp`?

In [33]:
#ANSWER
bikes[0:4]['atemp']

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

In [34]:
bikes.atemp[:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

In [35]:
bikes['atemp'][:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [40]:
#print(bikes[[0]])
#bikes[0]
#bikes[0,0]
#E: bikes[[0,0]]

In [43]:
bikes[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

In [49]:
bikes[:2].iloc[0]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 1st row of the DataFrame by its index?

In [51]:
#ANSWER
bikes[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [53]:
#ANSWER
bikes.iloc[:,2].head(5)

0    1
1    1
2    1
3    1
4    1
Name: season, dtype: int64

In [64]:
bikes.iloc[1:8,2:6]


season  yr  mnth  hr
1       1   0     1   1
2       1   0     1   2
3       1   0     1   3
4       1   0     1   4
5       1   0     1   5
6       1   0     1   6
7       1   0     1   7

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [65]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [66]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [67]:
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [0]:
#ANSWER


What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [68]:
#ANSWER
def dev(num, divsor):
    if divsor == 0: 
        res = np.nan
    else:
        res = num / divsor
    return res

print(dev(1,0))

nan


Apply the Pandas `isna` function to the following data objects:

In [69]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [70]:
#ANSWER
print(pd.isna(x), pd.isna(y))

False True


In [71]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [72]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

? ANSWER: 

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [73]:
#ANSWER
bikes['season'].value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [74]:
#ANSWER
print('instant:', bikes['instant'].min(), 'to', bikes['instant'].max())
print('dteday:', bikes['dteday'].min(), 'to', bikes['dteday'].max())
print('windspeed:', bikes['windspeed'].min(), 'to', bikes['windspeed'].max())

instant: 1 to 17379
dteday: 2011-01-01 to 2012-12-31
windspeed: 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [76]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
instant       17379 non-null int64
dteday        17379 non-null object
season        17379 non-null int64
yr            17379 non-null int64
mnth          17379 non-null int64
hr            17379 non-null int64
holiday       17379 non-null int64
weekday       17379 non-null int64
workingday    17379 non-null int64
weathersit    17379 non-null int64
temp          17379 non-null float64
atemp         17379 non-null float64
hum           17379 non-null float64
windspeed     17379 non-null float64
casual        17379 non-null int64
registered    17379 non-null int64
cnt           17379 non-null int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [81]:
x = bikes.min()

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                0
workingday             0
weathersit             1
temp                0.02
atemp                  0
hum                    0
windspeed              0
casual                 0
registered             0
cnt                    1
dtype: object

In [84]:
max(bikes.min())

TypeError: '>' not supported between instances of 'str' and 'int'

In [79]:
bikes_min, bikes_max = (min(bikes.min()), max(bikes.max()))
bikes_min, bikes_max

TypeError: '<' not supported between instances of 'str' and 'int'

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [85]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [86]:
#ANSWER
bikes.quantile((0.1, 0.25, 0.5, 0.75, 0.9))

instant  season   yr  mnth    hr  holiday  weekday  workingday  \
0.10   1738.8     1.0  0.0   2.0   2.0      0.0      0.0         0.0   
0.25   4345.5     2.0  0.0   4.0   6.0      0.0      1.0         0.0   
0.50   8690.0     3.0  1.0   7.0  12.0      0.0      3.0         1.0   
0.75  13034.5     3.0  1.0  10.0  18.0      0.0      5.0         1.0   
0.90  15641.2     4.0  1.0  11.0  21.0      0.0      6.0         1.0   

      weathersit  temp   atemp   hum  windspeed  casual  registered    cnt  
0.10         1.0  0.24  0.2424  0.37     0.0000     1.0         7.0    9.0  
0.25         1.0  0.34  0.3333  0.48     0.1045     4.0        34.0   40.0  
0.50         1.0  0.50  0.4848  0.63     0.1940    17.0       115.0  142.0  
0.75         2.0  0.66  0.6212  0.78     0.2537    48.0       220.0  281.0  
0.90         2.0  0.74  0.6970  0.88     0.3582    92.0       354.0  451.2

In [87]:
bikes['atemp'].quantile([0.1, 0.25, 0.5, 0.75, 0.9])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [88]:
type(bikes['atemp'])

pandas.core.series.Series

In [89]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
10788    10789  2012-03-30       2   1     3  15        0        5   
872        873  2011-02-08       1   0     2  19        0        2   
2519      2520  2011-04-19       2   0     4  21        0        2   
3473      3474  2011-05-29       2   0     5  15        0        0   
14232    14233  2012-08-21       3   1     8   5        0        2   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
10788           1           3  0.42  0.4242  0.54     0.0000      73   
872             1           1  0.16  0.1212  0.40     0.4627       1   
2519            1           2  0.50  0.4848  0.72     0.1343       8   
3473            0           1  0.74  0.6970  0.70     0.2985     221   
14232           1           1  0.56  0.5303  0.83     0.0896       4   

       registered  cnt  
10788         207  280  
872           100  101  
2519          114  122  
3473          155  376  
14232          30   34

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [90]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [91]:
#ANSWER
type(atemp_level)

pandas.core.series.Series

Here is a random sample of `atemp_level`:

In [92]:
atemp_level.sample(5)          

6697        (0.5, 0.75]
9415        (0.25, 0.5]
1394     (-0.001, 0.25]
12159       (0.5, 0.75]
7768        (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [97]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(10)          

3800     warm
6337     warm
8786     mild
2324     warm
7948     mild
160      cool
14088    warm
12934    warm
13677    warm
9374     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [103]:
bikes['atemp_level'] = atemp_level

In [104]:
bikes.atemp_level.head()

0    mild
1    mild
2    mild
3    mild
4    mild
Name: atemp_level, dtype: category
Categories (4, object): [cool < mild < warm < hot]

In [106]:
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].season.count()

1829

In [108]:
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].count()

instant        1829
dteday         1829
season         1829
yr             1829
mnth           1829
hr             1829
holiday        1829
weekday        1829
workingday     1829
weathersit     1829
temp           1829
atemp          1829
hum            1829
windspeed      1829
casual         1829
registered     1829
cnt            1829
atemp_level    1829
dtype: int64

In [109]:
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].value_counts()

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [110]:
type(bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)])

pandas.core.frame.DataFrame

In [111]:
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].season.value_counts()

2    1829
Name: season, dtype: int64

In [112]:
# value_counts()  only used for pd.Series!!!!!!

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [113]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [115]:
print(a, type(a))

[0. 0. 0.] <class 'numpy.ndarray'>


In [116]:
print(b, type(b))

[[1. 1. 1.]] <class 'numpy.ndarray'>


In [117]:
print(c, type(c))

[[[9 5 3 2]
  [6 4 8 8]
  [5 2 2 4]]

 [[1 9 5 1]
  [2 3 7 8]
  [1 1 9 8]]] <class 'numpy.ndarray'>


In [118]:
print(d, type(d))

[0 1 2 3] <class 'numpy.ndarray'>


In [119]:
print(e, type(e))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [121]:
df = pd.read_csv('rock.csv')
df.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [122]:
df.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [123]:
def clean_column_names(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        clean_column_names.append(c)
        
    return clean_column_names

In [125]:
df.columns = clean_column_names(df.columns)

In [126]:
df.head(3)

song_clean artist_clean release_year  \
0  Caught Up in You  .38 Special         1982   
1      Fantasy Girl  .38 Special          NaN   
2   Hold On Loosely  .38 Special         1981   

                          combined  first  year  playcount  fg  
0  Caught Up in You by .38 Special      1     1         82  82  
1      Fantasy Girl by .38 Special      1     0          3   0  
2   Hold On Loosely by .38 Special      1     1         85  85

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [127]:
df.isnull().sum()

song_clean        0
artist_clean      0
release_year    577
combined          0
first             0
year              0
playcount         0
fg                0
dtype: int64

In [128]:
null_mask = df['release_year'].isnull()

In [130]:
null_mask.head()

0    False
1     True
2    False
3    False
4    False
Name: release_year, dtype: bool

In [132]:
df.loc[null_mask, 'release_year'] = 0

In [133]:
df.isnull().sum()

song_clean      0
artist_clean    0
release_year    0
combined        0
first           0
year            0
playcount       0
fg              0
dtype: int64

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
song_clean      2230 non-null object
artist_clean    2230 non-null object
release_year    2230 non-null object
combined        2230 non-null object
first           2230 non-null int64
year            2230 non-null int64
playcount       2230 non-null int64
fg              2230 non-null int64
dtypes: int64(4), object(4)
memory usage: 139.5+ KB


In [135]:
# check the value of release_year

df['release_year'].value_counts()

0                577
1973             104
1975              83
1977              83
1970              81
1971              75
1969              72
1980              70
1978              64
1979              63
1981              61
1967              61
1983              60
1976              56
1982              54
1984              51
1972              50
1974              48
1968              46
1987              39
1985              39
1986              37
1991              34
1989              32
1966              30
1988              29
1965              28
1994              25
1990              22
1993              19
1992              14
1964              14
1999              13
1995              10
1996               9
1963               9
1997               9
2002               6
1998               6
2005               5
2012               5
2004               5
2001               4
1962               3
2000               3
2008               3
2011               3
2003         

In [136]:
song_mask = df['release_year'] =='SONGFACTS.COM'


In [137]:
df.loc[song_mask, 'release_year'] = np.nan

In [140]:
df.release_year.value_counts()

0       577
1973    104
1975     83
1977     83
1970     81
1971     75
1969     72
1980     70
1978     64
1979     63
1981     61
1967     61
1983     60
1976     56
1982     54
1984     51
1972     50
1974     48
1968     46
1987     39
1985     39
1986     37
1991     34
1989     32
1966     30
1988     29
1965     28
1994     25
1990     22
1993     19
1992     14
1964     14
1999     13
1995     10
1996      9
1963      9
1997      9
2002      6
1998      6
2005      5
2004      5
2012      5
2001      4
1962      3
2007      3
2011      3
2008      3
2000      3
2003      3
2013      2
2014      2
1961      1
1958      1
1071      1
2006      1
1955      1
Name: release_year, dtype: int64

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [141]:
df.describe()

first         year    playcount           fg
count  2230.0  2230.000000  2230.000000  2230.000000
mean      1.0     0.741256    16.872646    15.048430
std       0.0     0.438043    25.302972    25.288366
min       1.0     0.000000     0.000000     0.000000
25%       1.0     0.000000     1.000000     0.000000
50%       1.0     1.000000     4.000000     3.000000
75%       1.0     1.000000    21.000000    18.000000
max       1.0     1.000000   142.000000   142.000000

In [142]:
def check_min_max(data):
    print(data.describe().T[['min','max']])

In [143]:
check_min_max(df)

           min    max
first      1.0    1.0
year       0.0    1.0
playcount  0.0  142.0
fg         0.0  142.0


# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
song_clean      2230 non-null object
artist_clean    2230 non-null object
release_year    2229 non-null object
combined        2230 non-null object
first           2230 non-null int64
year            2230 non-null int64
playcount       2230 non-null int64
fg              2230 non-null int64
dtypes: int64(4), object(4)
memory usage: 139.5+ KB


In [148]:
def print_out(data_row):
    print('Song: ', data_row['song_clean'])
    print('Artist: ', data_row['artist_clean'])
    print('whether or not the release date is < 1970: ', int(data_row['release_year'])<1970)
    print('\n')

In [149]:
print_out(df.iloc[4])

Song:  Art For Arts Sake
Artist:  10cc
whether or not the release date is < 1970:  False




In [155]:
df.iloc[4]

song_clean              Art For Arts Sake
artist_clean                         10cc
release_year                         1975
combined        Art For Arts Sake by 10cc
first                                   1
year                                    1
playcount                               1
fg                                      1
Name: 4, dtype: object

In [158]:
df.head().apply(print_out, axis=1)

Song:  Caught Up in You
Artist:  .38 Special
whether or not the release date is < 1970:  False


Song:  Fantasy Girl
Artist:  .38 Special
whether or not the release date is < 1970:  True


Song:  Hold On Loosely
Artist:  .38 Special
whether or not the release date is < 1970:  False


Song:  Rockin' Into the Night
Artist:  .38 Special
whether or not the release date is < 1970:  False


Song:  Art For Arts Sake
Artist:  10cc
whether or not the release date is < 1970:  False




0    None
1    None
2    None
3    None
4    None
dtype: object

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [163]:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

## Apply these functions to your dataset

In [164]:
df.apply(convert_to_float)

song_clean  artist_clean  release_year  combined  first  year  \
0            NaN           NaN        1982.0       NaN      1     1   
1            NaN           NaN           0.0       NaN      1     0   
2            NaN           NaN        1981.0       NaN      1     1   
3            NaN           NaN        1980.0       NaN      1     1   
4            NaN           NaN        1975.0       NaN      1     1   
5            NaN           NaN        2000.0       NaN      1     1   
6            NaN           NaN        2000.0       NaN      1     1   
7            NaN           NaN        2002.0       NaN      1     1   
8            NaN           NaN        1992.0       NaN      1     1   
9            NaN           NaN        1985.0       NaN      1     1   
10           NaN           NaN           0.0       NaN      1     0   
11           NaN           NaN        1980.0       NaN      1     1   
12           NaN           NaN        1993.0       NaN      1     1   
13           NaN           NaN           0.0       NaN      1     0   
14           NaN           NaN        1976.0       NaN      1     1   
15           NaN           NaN        1981.0       NaN      1     1   
16           NaN           NaN           0.0       NaN      1     0   
17           NaN           NaN        1995.0       NaN      1     1   
18           NaN           NaN        1980.0       NaN      1     1   
19           NaN           NaN        1980.0       NaN      1     1   
20           NaN           NaN        1979.0       NaN      1     1   
21           NaN           NaN        1975.0       NaN      1     1   
22           NaN           NaN        1984.0       NaN      1     1   
23           NaN           NaN        1977.0       NaN      1     1   
24           NaN           NaN           0.0       NaN      1     0   
25           NaN           NaN           0.0       NaN      1     0   
26           NaN           NaN           0.0       NaN      1     0   
27           NaN           NaN        1979.0       NaN      1     1   
28           NaN           NaN        1980.0       NaN      1     1   
29           NaN           NaN           0.0       NaN      1     0   
...          ...           ...           ...       ...    ...   ...   
2200         NaN           NaN        1983.0       NaN      1     1   
2201         NaN           NaN        1971.0       NaN      1     1   
2202         NaN           NaN        1971.0       NaN      1     1   
2203         NaN           NaN           0.0       NaN      1     0   
2204         NaN           NaN        1971.0       NaN      1     1   
2205         NaN           NaN           0.0       NaN      1     0   
2206         NaN           NaN           0.0       NaN      1     0   
2207         NaN           NaN        1968.0       NaN      1     1   
2208         NaN           NaN           0.0       NaN      1     0   
2209         NaN           NaN        1976.0       NaN      1     1   
2210         NaN           NaN        1973.0       NaN      1     1   
2211         NaN           NaN        1980.0       NaN      1     1   
2212         NaN           NaN        1983.0       NaN      1     1   
2213         NaN           NaN        1983.0       NaN      1     1   
2214         NaN           NaN        1975.0       NaN      1     1   
2215         NaN           NaN           0.0       NaN      1     0   
2216         NaN           NaN           0.0       NaN      1     0   
2217         NaN           NaN        1973.0       NaN      1     1   
2218         NaN           NaN           0.0       NaN      1     0   
2219         NaN           NaN        1973.0       NaN      1     1   
2220         NaN           NaN        1983.0       NaN      1     1   
2221         NaN           NaN           0.0       NaN      1     0   
2222         NaN           NaN           0.0       NaN      1     0   
2223         NaN           NaN        1981.0       NaN      1     1   
2224         NaN           NaN

## Describe the new float-only DataFrame.

In [165]:
df.describe().T

count       mean        std  min  25%  50%   75%    max
first      2230.0   1.000000   0.000000  1.0  1.0  1.0   1.0    1.0
year       2230.0   0.741256   0.438043  0.0  0.0  1.0   1.0    1.0
playcount  2230.0  16.872646  25.302972  0.0  1.0  4.0  21.0  142.0
fg         2230.0  15.048430  25.288366  0.0  0.0  3.0  18.0  142.0



> 
>
>




>


>


>




---



---

> > > > > > > >   © 2019 Data Science Institute of Australia


---



---

